"""add login lockout fields

Revision ID: 5e662027ac02
Revises: a50ebe04e242
Create Date: 2026-08-07 16:00:55.777014
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa

revision: str = '5e662027ac02'
down_revision: Union[str, None] = 'a50ebe04e242'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'users',
        sa.Column('failed_login_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    )
    op.add_column('users', sa.Column('locked_until', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'locked_until')
    op.drop_column('users', 'failed_login_count')
    # ### end Alembic commands ###
