"""add service accounts

Revision ID: 7272bd87485b
Revises: 4ea1b81de354
Create Date: 2026-08-07 13:10:01.801659
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa

revision: str = '7272bd87485b'
down_revision: Union[str, None] = '4ea1b81de354'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('service_accounts',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_service_accounts_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_service_accounts')),
    sa.UniqueConstraint('code', name=op.f('uq_service_accounts_code')),
    sa.UniqueConstraint('user_id', name=op.f('uq_service_accounts_user_id'))
    )
    op.create_table('service_account_permissions',
    sa.Column('service_account_id', sa.UUID(), nullable=False),
    sa.Column('permission_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], name=op.f('fk_service_account_permissions_permission_id_permissions'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['service_account_id'], ['service_accounts.id'], name=op.f('fk_service_account_permissions_service_account_id_service_accounts'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('service_account_id', 'permission_id', name=op.f('pk_service_account_permissions'))
    )
    op.create_table('service_api_keys',
    sa.Column('service_account_id', sa.UUID(), nullable=False),
    sa.Column('key_prefix', sa.String(length=16), nullable=False),
    sa.Column('secret_hash', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['service_account_id'], ['service_accounts.id'], name=op.f('fk_service_api_keys_service_account_id_service_accounts'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_service_api_keys')),
    sa.UniqueConstraint('secret_hash', name=op.f('uq_service_api_keys_secret_hash'))
    )
    op.create_index(op.f('ix_service_api_keys_key_prefix'), 'service_api_keys', ['key_prefix'], unique=False)
    op.create_index(op.f('ix_service_api_keys_service_account_id'), 'service_api_keys', ['service_account_id'], unique=False)
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_service_api_keys_service_account_id'), table_name='service_api_keys')
    op.drop_index(op.f('ix_service_api_keys_key_prefix'), table_name='service_api_keys')
    op.drop_table('service_api_keys')
    op.drop_table('service_account_permissions')
    op.drop_table('service_accounts')
    # ### end Alembic commands ###

