"""add outbound connectors

Revision ID: 7edc10782345
Revises: 7272bd87485b
Create Date: 2026-08-07 13:24:16.641119
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
revision: str = '7edc10782345'
down_revision: Union[str, None] = '7272bd87485b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('outbound_connectors',
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('base_url', sa.String(length=500), nullable=False),
    sa.Column('allowed_host', sa.String(length=253), nullable=False),
    sa.Column('auth_type', sa.String(length=32), nullable=False),
    sa.Column('encrypted_credentials', sa.Text(), nullable=True),
    sa.Column('health_path', sa.String(length=500), nullable=False),
    sa.Column('timeout_seconds', sa.Integer(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_outbound_connectors')),
    sa.UniqueConstraint('code', name=op.f('uq_outbound_connectors_code'))
    )
    op.create_table('outbound_call_logs',
    sa.Column('connector_id', sa.UUID(), nullable=False),
    sa.Column('operation', sa.String(length=100), nullable=False),
    sa.Column('method', sa.String(length=16), nullable=False),
    sa.Column('url_path', sa.String(length=500), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('http_status', sa.Integer(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('response_excerpt', sa.Text(), nullable=True),
    sa.Column('request_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['connector_id'], ['outbound_connectors.id'], name=op.f('fk_outbound_call_logs_connector_id_outbound_connectors'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_outbound_call_logs'))
    )
    op.create_index(op.f('ix_outbound_call_logs_connector_id'), 'outbound_call_logs', ['connector_id'], unique=False)
    op.create_index(op.f('ix_outbound_call_logs_operation'), 'outbound_call_logs', ['operation'], unique=False)
    op.create_index(op.f('ix_outbound_call_logs_status'), 'outbound_call_logs', ['status'], unique=False)
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_outbound_call_logs_status'), table_name='outbound_call_logs')
    op.drop_index(op.f('ix_outbound_call_logs_operation'), table_name='outbound_call_logs')
    op.drop_index(op.f('ix_outbound_call_logs_connector_id'), table_name='outbound_call_logs')
    op.drop_table('outbound_call_logs')
    op.drop_table('outbound_connectors')
    # ### end Alembic commands ###

