"""add outbound task queue

Revision ID: a50ebe04e242
Revises: 7edc10782345
Create Date: 2026-08-07 13:37:47.200750
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
revision: str = 'a50ebe04e242'
down_revision: Union[str, None] = '7edc10782345'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('outbound_tasks',
    sa.Column('connector_id', sa.UUID(), nullable=False),
    sa.Column('operation', sa.String(length=100), nullable=False),
    sa.Column('method', sa.String(length=16), nullable=False),
    sa.Column('url_path', sa.String(length=500), nullable=False),
    sa.Column('body', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('idempotency_key', sa.String(length=128), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('attempt_count', sa.Integer(), nullable=False),
    sa.Column('max_attempts', sa.Integer(), nullable=False),
    sa.Column('next_attempt_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('last_http_status', sa.Integer(), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['connector_id'], ['outbound_connectors.id'], name=op.f('fk_outbound_tasks_connector_id_outbound_connectors'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_outbound_tasks')),
    sa.UniqueConstraint('idempotency_key', name=op.f('uq_outbound_tasks_idempotency_key')),
    sa.UniqueConstraint('idempotency_key', name=op.f('uq_outbound_tasks_idempotency_key'))
    )
    op.create_index(op.f('ix_outbound_tasks_connector_id'), 'outbound_tasks', ['connector_id'], unique=False)
    op.create_index(op.f('ix_outbound_tasks_next_attempt_at'), 'outbound_tasks', ['next_attempt_at'], unique=False)
    op.create_index(op.f('ix_outbound_tasks_operation'), 'outbound_tasks', ['operation'], unique=False)
    op.create_index(op.f('ix_outbound_tasks_status'), 'outbound_tasks', ['status'], unique=False)
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_outbound_tasks_status'), table_name='outbound_tasks')
    op.drop_index(op.f('ix_outbound_tasks_operation'), table_name='outbound_tasks')
    op.drop_index(op.f('ix_outbound_tasks_next_attempt_at'), table_name='outbound_tasks')
    op.drop_index(op.f('ix_outbound_tasks_connector_id'), table_name='outbound_tasks')
    op.drop_table('outbound_tasks')
    # ### end Alembic commands ###

